ALTER TABLE users ADD COLUMN IF NOT EXISTS streak_count  INT  NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS streak_last   DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS streak_reward INT  NOT NULL DEFAULT 0;
