export type Smp = "image" | "tarot" | "song" | "text";
export interface SkuInfo { flow: string; ask: string; smp: Smp; sp: string; desc: { en: string; ru: string; es: string }; }

// sp = short EN prompt that produces a SHORT teaser sample (the paid version is the full thing)
export const BUNDLES: Record<string, string[]> = {
  bundle_romance: ["poem", "love_letter", "image"],
  bundle_mystic: ["astro_full", "name_secrets", "tarot"],
};

export const SKU_INFO: Record<string, SkuInfo> = {
  music_card: { flow: "collect_prompt", ask: "ask_musiccard", smp: "image",
    sp: "a warm tasteful greeting-card illustration, soft light, elegant, no text",
    desc: {
      en: "🎬 <b>Living Musical Card</b> — a real short VIDEO greeting: AIfa paints a beautiful card image for your occasion and composes a gentle instrumental, then blends them into a square MP4 you can play and forward in any chat. A little movie-gift that feels alive — far more special than a static picture.",
      ru: "🎬 <b>Живая музыкальная открытка</b> — настоящее короткое ВИДЕО-поздравление: AIfa рисует красивую открытку под твой повод и сочиняет нежную музыку, а затем соединяет их в квадратный MP4, который можно проигрывать и пересылать в любом чате. Маленький фильм-подарок, который ощущается живым — куда особеннее статичной картинки.",
      es: "🎬 <b>Tarjeta Musical Viva</b> — un VÍDEO de felicitación corto: AIfa pinta una tarjeta para tu ocasión y compone una música suave, y los une en un MP4 cuadrado para reproducir y reenviar. Un mini regalo-película que se siente vivo." } },
  bundle_romance: { flow: "collect_prompt", ask: "ask_bundle", smp: "text",
    sp: "In 3 short sentences, give a warm teaser of a romantic gift set (a poem, a love letter and a picture) for a beloved. English.",
    desc: {
      en: "💝 <b>Romantic Bundle</b> — three gifts in one, at a sweet discount: a personal <b>poem</b>, a tender <b>love letter</b>, and a beautiful romantic <b>image</b>, all created around the same person and feeling. Tell us who it's for and what's in your heart, and AIfa crafts the whole set so it arrives together as one heartfelt surprise. Perfect for an anniversary, a confession, or simply to make someone feel deeply loved.",
      ru: "💝 <b>Романтический набор</b> — три подарка в одном, со скидкой: персональный <b>стих</b>, нежное <b>любовное письмо</b> и красивое романтическое <b>изображение</b>, созданные вокруг одного человека и одного чувства. Расскажи, кому и что у тебя на сердце — и AIfa соберёт весь набор, чтобы он пришёл вместе, как один трогательный сюрприз. Идеально для годовщины, признания или просто чтобы человек почувствовал, как сильно он любим.",
      es: "💝 <b>Pack Romántico</b> — tres regalos en uno, con descuento: un <b>poema</b> personal, una tierna <b>carta de amor</b> y una <b>imagen</b> romántica, creados en torno a la misma persona y sentimiento. Dinos para quién es y AIfa arma todo el set. Perfecto para un aniversario o una confesión." } },
  bundle_mystic: { flow: "collect_prompt", ask: "ask_bundle", smp: "text",
    sp: "In 3 short sentences, give a warm teaser of a mystical gift set (astrology, name secrets and a tarot reading) for a person. English.",
    desc: {
      en: "🔮 <b>Mystic Bundle</b> — three mystical readings in one, at a discount: a personal <b>astrology</b> reading, the hidden <b>secrets of the name</b>, and a real 3-card <b>tarot</b> spread. Give a name and birth date (and a question for the cards), and AIfa prepares the whole mystical portrait so it arrives together. A captivating gift for anyone who loves the stars, symbols and a touch of magic.",
      ru: "🔮 <b>Мистический набор</b> — три мистических разбора в одном, со скидкой: персональная <b>астрология</b>, скрытые <b>тайны имени</b> и настоящий расклад <b>таро на 3 карты</b>. Назови имя и дату рождения (и вопрос для карт) — и AIfa подготовит весь мистический портрет, чтобы он пришёл вместе. Завораживающий подарок для всех, кто любит звёзды, символы и щепотку магии.",
      es: "🔮 <b>Pack Místico</b> — tres lecturas místicas en una, con descuento: <b>astrología</b> personal, los <b>secretos del nombre</b> y una tirada real de <b>tarot</b> de 3 cartas. Da un nombre y fecha de nacimiento, y AIfa prepara todo el retrato místico. Un regalo cautivador para quien ama las estrellas." } },
  astro_full: { flow: "collect_astro_full", ask: "ask_astro", smp: "text",
    sp: "In 3 short sentences give a warm astrology teaser for a Pisces named Maria. English.",
    desc: {
      en: "🔮 <b>Astrology</b> — a deep, personal astrological reading drawn from your name and date of birth. AIfa finds your sign, reveals your character and the hidden strengths you carry, speaks to your tendencies in love, money, career and health, and shows exactly what the stars are highlighting for you right now. This is not a dry newspaper horoscope but a warm, detailed text written as if just for you — a mirror you actually recognise yourself in. A beautiful way to understand yourself more deeply, or to give someone close a truly thoughtful gift.",
      ru: "🔮 <b>Астрология</b> — глубокий персональный астрологический разбор по твоему имени и дате рождения. AIfa определяет твой знак, раскрывает характер и скрытые сильные стороны, говорит о тенденциях в любви, деньгах, карьере и здоровье и показывает, на что именно сейчас указывают звёзды. Это не сухой гороскоп из газеты, а тёплый, подробный текст, написанный будто специально для тебя — зеркало, в котором ты действительно узнаёшь себя. Прекрасный способ глубже понять себя или сделать по-настоящему трогательный подарок близкому.",
      es: "🔮 <b>Astrología</b> — una lectura astrológica personal y profunda a partir de tu nombre y fecha de nacimiento. AIfa halla tu signo, revela tu carácter y tus fortalezas ocultas, y habla de tus tendencias en amor, dinero, carrera y salud, mostrando lo que las estrellas destacan para ti ahora. No es un horóscopo de periódico, sino un texto cálido y detallado, escrito como si fuera solo para ti. Una forma hermosa de conocerte o de hacer un regalo conmovedor." } },
  song: { flow: "collect_song", ask: "ask_song", smp: "song",
    sp: "Write 4 short lines of warm, catchy song lyrics about a birthday for a friend named Alex. English.",
    desc: {
      en: "🎵 <b>Instrumental track</b> — your own one-of-a-kind piece of music, 2–3 minutes long, composed by AI specifically for your occasion and mood. Describe what you want — a tender lullaby, a driving workout beat, a romantic theme for a date, or background music for your video — and AIfa writes a unique composition from scratch. You receive a finished audio file with its own cover art, ready to listen to, gift, or use anywhere you like. This is not a remix of someone else's songs but real, original music, born for your story alone.",
      ru: "🎵 <b>Инструментал</b> — твой собственный, нигде больше не существующий музыкальный трек на 2–3 минуты, написанный искусственным интеллектом специально под твой повод и настроение. Опиши, что хочешь — нежную колыбельную, драйвовый бит для тренировки, романтическую тему для свидания или фоновую музыку для видео — и AIfa сочинит уникальную композицию с нуля. Ты получаешь готовый аудиофайл с собственной обложкой, который можно слушать, дарить и использовать где угодно. Это не нарезка из чужих песен, а настоящая авторская музыка, рождённая только под твою историю.",
      es: "🎵 <b>Pista instrumental</b> — tu propia composición única de 2–3 minutos, creada por IA especialmente para tu ocasión y ánimo. Describe lo que quieras — una nana, un beat para entrenar, un tema romántico o música de fondo — y AIfa la compone desde cero. Recibes un audio terminado con su propia portada, listo para escuchar, regalar o usar. No es un remix, sino música original nacida solo para tu historia." } },
  song_vocal: { flow: "collect_prompt", ask: "ask_vocal", smp: "song",
    sp: "Write 4 short lines of heartfelt song lyrics with vocals about love. English.",
    desc: {
      en: "🎤 <b>Song with vocals</b> — the most personal gift of all: a real song, around three minutes long, with lyrics written for your moment and a live singing voice that performs them. Tell us who it's for and why — a birthday, an anniversary, a confession, a word of support in a hard time — and AIfa writes the words, composes the melody, and sings them into a finished MP3. It becomes a track your person replays and treasures for years, long after the flowers have faded. Imagine their face the moment they realise this song was written personally about them.",
      ru: "🎤 <b>Песня с вокалом</b> — самый личный подарок из всех: настоящая песня примерно на три минуты, с написанным под твой момент текстом и живым поющим голосом, который её исполняет. Расскажи, кому и по какому поводу — день рождения, годовщина, признание, слова поддержки в трудную минуту — и AIfa сочинит слова, придумает мелодию и споёт их в готовый MP3. Это трек, который человек будет переслушивать и хранить годами, когда цветы давно завянут. Представь его лицо в тот миг, когда он поймёт, что эта песня написана лично про него.",
      es: "🎤 <b>Canción con voz</b> — el regalo más personal: una canción real de unos tres minutos, con letra escrita para tu momento y una voz que la canta. Dinos para quién y por qué — un cumpleaños, un aniversario, una confesión, un apoyo — y AIfa crea las palabras, la melodía y las canta en un MP3 terminado. Un tema que se atesora durante años. Imagina su cara al descubrir que la canción habla de él." } },
  name_secrets: { flow: "collect_name", ask: "ask_name", smp: "text",
    sp: "Reveal in 3 short sentences the hidden meaning, energy and a lucky trait of the name 'Sofia'. Warm, mystical. English.",
    desc: {
      en: "🔤 <b>Secrets of the name</b> — a fascinating journey into the depth of any name. AIfa uncovers its historical meaning and origin, its hidden energy and vibration, the strengths of character it tends to give its bearer, the lucky symbols tied to it, and the quiet hints of destiny it carries. Give your own name or that of someone dear, and receive a beautiful, personal word-portrait you genuinely recognise. It makes a warm greeting, a thoughtful surprise, or simply a delightful way to see a familiar name with new eyes.",
      ru: "🔤 <b>Тайны имени</b> — увлекательное путешествие в глубину любого имени. AIfa раскрывает его историческое значение и происхождение, скрытую энергетику и вибрацию, сильные черты характера, которые оно обычно дарит своему носителю, связанные с ним счастливые символы и тихие подсказки судьбы. Назови своё имя или имя дорогого человека — и получишь красивый, личный текст-портрет, в котором по-настоящему узнаёшь себя. Это и тёплое поздравление, и продуманный сюрприз, и просто радость увидеть знакомое имя новыми глазами.",
      es: "🔤 <b>Secretos del nombre</b> — un viaje fascinante a la profundidad de cualquier nombre. AIfa revela su significado e historia, su energía oculta, las fortalezas que suele dar a quien lo lleva, sus símbolos de suerte y sus pistas de destino. Da tu nombre o el de un ser querido y recibe un retrato personal en palabras en el que te reconoces. Un saludo cálido o una sorpresa con encanto." } },
  image: { flow: "collect_image", ask: "ask_image", smp: "image",
    sp: "a cozy magical birthday scene, warm light, balloons, tasteful, beautiful. No text.",
    desc: {
      en: "🖼 <b>Image on request</b> — a unique, high-quality picture created by AI exactly from your description. Want a birthday card, a fairy-tale portrait, a fantasy landscape, art for your avatar, or an illustration of an idea in your head? Just describe it in words and AIfa paints it from scratch, in the style and mood you ask for. No watermarks and no broken lettering — a clean, beautiful image ready to print, post, or send as a gift. Your imagination turns into a finished picture in just a few seconds.",
      ru: "🖼 <b>Изображение по запросу</b> — уникальная картинка высокого качества, созданная искусственным интеллектом точно по твоему описанию. Хочешь открытку ко дню рождения, сказочный портрет, фантастический пейзаж, арт для аватара или иллюстрацию идеи из головы? Просто опиши это словами — и AIfa нарисует с нуля, в нужном стиле и настроении. Без водяных знаков и кривых надписей — чистое, красивое изображение, готовое к печати, публикации или отправке в подарок. Твоя фантазия превращается в готовую картинку всего за несколько секунд.",
      es: "🖼 <b>Imagen a pedido</b> — una imagen única de alta calidad creada por IA exactamente según tu descripción. ¿Quieres una tarjeta, un retrato de fantasía, un paisaje, arte para tu avatar o la ilustración de una idea? Descríbelo y AIfa lo pinta desde cero, con el estilo y ánimo que pidas. Sin marcas de agua ni texto roto: una imagen limpia lista para imprimir o regalar, en segundos." } },
  poem: { flow: "collect_prompt", ask: "ask_poem", smp: "text",
    sp: "Write a short 4-line warm personal poem for a mother's birthday. English.",
    desc: {
      en: "📝 <b>Personal poem</b> — a poem written specifically for your person and your occasion. Tell us who it's for, what you feel, and the mood you need — tenderness, gratitude, a birthday cheer, a quiet confession — and AIfa finds the words, the rhyme and the rhythm that land right in the heart. You get a finished, polished text you can send, read aloud at a celebration, or tuck inside a card. Poems always touch far deeper when every line is clearly about one real, beloved person.",
      ru: "📝 <b>Персональный стих</b> — стихотворение, написанное специально под твоего человека и твой повод. Расскажи, кому он посвящён, что ты чувствуешь и какое настроение нужно — нежность, благодарность, поздравление, тихое признание — и AIfa подберёт слова, рифму и ритм, которые попадут прямо в сердце. Ты получаешь готовый, отточенный текст, который можно отправить, прочитать вслух на празднике или вложить в открытку. Стихи трогают куда сильнее, когда каждая строчка явно про одного конкретного, любимого человека.",
      es: "📝 <b>Poema personal</b> — un poema escrito específicamente para tu persona y tu ocasión. Dinos para quién es, qué sientes y el ánimo que buscas — ternura, gratitud, felicitación, una confesión — y AIfa encuentra las palabras, la rima y el ritmo que llegan al corazón. Recibes un texto pulido y listo para enviar, leer en voz alta o poner en una tarjeta. Los poemas conmueven más cuando hablan de una persona real." } },
  love_letter: { flow: "collect_prompt", ask: "ask_letter", smp: "text",
    sp: "Write 3 short tender sentences of a love letter. English.",
    desc: {
      en: "💌 <b>Love letter</b> — a tender, sincere and eloquent letter that says what is so hard to put into words yourself. Share a few details about your beloved and your feelings, and AIfa weaves them into touching lines in your own voice — from the first flutter of falling in love to deep, settled devotion. The result is a letter worth rereading and keeping forever, the kind people press between the pages of a book. Perfect for a confession, an anniversary, or simply to remind someone how deeply they are loved.",
      ru: "💌 <b>Любовное письмо</b> — нежное, искреннее и красноречивое письмо, которое скажет то, что так трудно выразить самому. Поделись парой деталей о любимом человеке и своих чувствах — и AIfa сплетёт из них трогательные строки в твоём собственном тоне, от первого трепета влюблённости до глубокой, спокойной преданности. Получается письмо, которое хочется перечитывать и хранить всегда — из тех, что вкладывают между страниц книги. Идеально для признания, годовщины или просто чтобы напомнить, как сильно человек любим.",
      es: "💌 <b>Carta de amor</b> — una carta tierna, sincera y elocuente que dice lo difícil de expresar uno mismo. Comparte unos detalles sobre tu amor y tus sentimientos, y AIfa los teje en líneas conmovedoras con tu propia voz, desde el primer enamoramiento hasta la devoción más honda. Una carta para releer y guardar siempre. Perfecta para una confesión o un aniversario." } },
  dream: { flow: "collect_prompt", ask: "ask_dream", smp: "text",
    sp: "Briefly interpret in 3 sentences a dream about flying over the sea. Warm, insightful. English.",
    desc: {
      en: "🌙 <b>Dream interpretation</b> — a thoughtful, symbolic reading of your dream. Describe what you saw while sleeping and AIfa unfolds the possible meanings of its images, connecting them to your emotions, your current life situation, and what may be quietly taking shape ahead. This is no clichéd 'dream dictionary' but a deep, warm interpretation that helps you hear the hint your subconscious is offering. Sometimes a single dream knows more about us than we are ready to admit to ourselves.",
      ru: "🌙 <b>Толкование сна</b> — вдумчивый, символический разбор твоего сна. Опиши, что ты видел во сне, и AIfa раскроет возможные значения его образов, связав их с твоими чувствами, текущей жизненной ситуацией и тем, что, может быть, тихо складывается впереди. Это не банальный «сонник», а глубокая, тёплая интерпретация, которая помогает услышать подсказку, что предлагает подсознание. Иногда один сон знает о нас больше, чем мы готовы признать сами.",
      es: "🌙 <b>Interpretación de sueños</b> — una lectura simbólica y reflexiva de tu sueño. Describe lo que viste al dormir y AIfa despliega los posibles significados de sus imágenes, ligándolos a tus emociones, tu situación actual y lo que se gesta por venir. No es un 'diccionario de sueños', sino una interpretación profunda y cálida que te ayuda a oír lo que dice tu subconsciente." } },
  compatibility: { flow: "collect_prompt", ask: "ask_compat", smp: "text",
    sp: "In 3 sentences, give a warm compatibility teaser for Anna and Mark. English.",
    desc: {
      en: "❤️ <b>Couple compatibility</b> — a warm and insightful reading of the bond between two people. Give two names (and their signs or birth dates if you know them) and AIfa describes your chemistry, the real strengths of your union, the magnetic points that draw you together and the areas worth handling with care, finishing with kind, practical advice. It works beautifully for lovers, for close friends, or simply out of curiosity. A gentle, sincere look at what truly connects two hearts.",
      ru: "❤️ <b>Совместимость пары</b> — тёплый и проницательный разбор связи между двумя людьми. Назови два имени (и знаки или даты рождения, если знаешь) — и AIfa расскажет о вашей химии, настоящих сильных сторонах союза, точках притяжения, что тянут вас друг к другу, и о зонах, где стоит быть бережнее, и завершит добрым, практичным советом. Это прекрасно работает и для влюблённых, и для близких друзей, и просто из любопытства. Мягкий, искренний взгляд на то, что по-настоящему связывает два сердца.",
      es: "❤️ <b>Compatibilidad de pareja</b> — una lectura cálida y perceptiva del vínculo entre dos personas. Da dos nombres (y sus signos o fechas si los sabes) y AIfa describe vuestra química, las fortalezas reales de la unión, los puntos de atracción y las zonas a cuidar, con un consejo amable. Ideal para parejas, amigos o por curiosidad. Una mirada sincera a lo que une dos corazones." } },
  tarot: { flow: "collect_prompt", ask: "ask_tarot", smp: "tarot",
    sp: "",
    desc: {
      en: "🃏 <b>3-card Tarot</b> — a genuine spread for the question on your mind. Ask what matters to you and AIfa draws three real Rider-Waite cards in the positions Past · Present · Future, shows you the image of each one, and gives a deep, clear interpretation tailored to your exact situation, ending with concrete guidance. This is not just a pretty picture — it is a living reading: you see the actual cards and read what they are telling you. A moment of magic and clarity for whenever you stand before a choice.",
      ru: "🃏 <b>Таро на 3 карты</b> — настоящий расклад на твой вопрос. Задай то, что волнует, — и AIfa вытянет три реальные карты колоды Уэйта в позициях Прошлое · Настоящее · Будущее, покажет изображение каждой из них и даст глубокую, понятную интерпретацию именно под твою ситуацию, завершив конкретным советом. Это не просто красивая картинка — это живой расклад: ты видишь сами карты и читаешь, что они тебе говорят. Момент магии и ясности всякий раз, когда стоишь перед выбором.",
      es: "🃏 <b>Tarot de 3 cartas</b> — una tirada real para tu pregunta. Pregunta lo que te importa y AIfa saca tres cartas reales de Rider-Waite en las posiciones Pasado · Presente · Futuro, te muestra la imagen de cada una y da una interpretación profunda y clara para tu situación, con un consejo concreto. No es solo una imagen bonita: es una lectura viva donde ves las cartas y lees lo que dicen. Magia y claridad ante cada decisión." } },
  tale: { flow: "collect_prompt", ask: "ask_tale", smp: "text",
    sp: "Write the opening 3 sentences of a magical personalized children's tale about a brave girl named Mia. English.",
    desc: {
      en: "📖 <b>Personal interactive tale</b> — a magical story of ten chapters in which the hero is you or your child. For every single chapter AIfa paints a unique illustration in one consistent visual style, and at the key turning points YOU decide where the plot will go next. The result is a living, unrepeatable adventure book built entirely around a specific person — their name, their age, and the things they love most. An unforgettable gift for a child, a sweetheart, or yourself: a fairy tale that exists nowhere else in the world.",
      ru: "📖 <b>Персональная интерактивная сказка</b> — волшебная история из десяти глав, в которой главный герой — ты или твой ребёнок. К каждой главе AIfa рисует уникальную иллюстрацию в едином визуальном стиле, а в ключевых поворотах ТЫ сам решаешь, куда дальше повернёт сюжет. Получается живая, неповторимая книга-приключение, построенная целиком вокруг конкретного человека — его имени, возраста и того, что он любит больше всего. Незабываемый подарок ребёнку, любимому или себе: сказка, которой больше нет нигде в мире.",
      es: "📖 <b>Cuento interactivo personal</b> — una historia mágica de diez capítulos donde el héroe eres tú o tu hijo. En cada capítulo AIfa pinta una ilustración única con un estilo visual coherente, y en los giros clave TÚ decides hacia dónde sigue la trama. El resultado es un libro de aventuras vivo e irrepetible, construido en torno a una persona concreta: su nombre, su edad y lo que más ama. Un regalo inolvidable: un cuento que no existe en ningún otro lugar." } },
  detective: { flow: "collect_prompt", ask: "ask_detective", smp: "text",
    sp: "Write the opening 3 sentences of an interactive detective mystery where the reader is the investigator. English.",
    desc: {
      en: "🕵️ <b>Interactive detective</b> — a gripping investigation in which YOU become the detective. AIfa builds a personal case for you, leads you from clue to clue and illustrates the unfolding story, while at every turn you make the decisions that bring you closer to cracking it. Every playthrough is unique and shaped entirely by the choices you make. Perfect for anyone who loves riddles, suspense, and finally being the hero at the centre of the mystery.",
      ru: "🕵️ <b>Интерактивный детектив</b> — захватывающее расследование, в котором ТЫ становишься сыщиком. AIfa создаёт персональное дело, ведёт тебя от улики к улике и иллюстрирует разворачивающийся сюжет, а на каждом повороте именно ты принимаешь решения, что приближают к разгадке. Каждое прохождение уникально и полностью зависит от твоих выборов. Идеально для тех, кто любит загадки, напряжение и наконец-то побыть героем в самом центре детектива.",
      es: "🕵️ <b>Detective interactivo</b> — una investigación apasionante en la que TÚ eres el detective. AIfa crea un caso personal, te lleva de pista en pista e ilustra la historia, y en cada giro tú tomas las decisiones que te acercan a resolverlo. Cada partida es única y depende por completo de tus elecciones. Perfecto para quien ama los enigmas, el suspenso y ser el héroe del misterio." } },
  year_ahead: { flow: "collect_prompt", ask: "ask_year", smp: "text",
    sp: "Give a short uplifting 3-sentence teaser of a personal year-ahead forecast for someone starting a new chapter. English.",
    desc: {
      en: "📅 <b>Your year ahead</b> — an enormous personal forecast covering the full twelve months ahead from today. AIfa writes a sweeping overview and then unfolds each of the twelve months and six areas of life in detail — love, money, career, health, personal growth and luck — creating a separate atmospheric illustration to accompany every month. That is more than 50,000 characters of warm, inspiring and concrete text, written personally for you. It is, quite literally, a whole private book about the year that is coming.",
      ru: "📅 <b>Твой год вперёд</b> — огромный персональный прогноз на все двенадцать месяцев вперёд от сегодняшнего дня. AIfa пишет масштабный обзор, а затем подробно раскрывает каждый из двенадцати месяцев и шесть сфер жизни — любовь, деньги, карьеру, здоровье, личностный рост и удачу, — создавая к каждому месяцу отдельную атмосферную иллюстрацию. Это более 50 000 символов тёплого, вдохновляющего и конкретного текста, написанного лично под тебя. Это в буквальном смысле целая личная книга о твоём наступающем годе.",
      es: "📅 <b>Tu año por delante</b> — un pronóstico personal enorme para los doce meses por venir desde hoy. AIfa escribe un panorama amplio y luego desarrolla en detalle cada uno de los doce meses y seis áreas de la vida — amor, dinero, carrera, salud, crecimiento y suerte — creando una ilustración atmosférica para cada mes. Son más de 50.000 caracteres de texto cálido, inspirador y concreto, escrito para ti. Literalmente, todo un libro personal sobre tu año que llega." } },
};

export function skuLabel(sku: string, lang: string): string {
  const info = SKU_INFO[sku]; if (!info) return sku;
  const dl = (lang === "ru" || lang === "es") ? lang : "en";
  const d = (info.desc as any)[dl] as string;
  const i = d.indexOf("</b>");
  return i > 0 ? d.slice(0, i + 4) : sku;
}
